language: python

python:
  - 3.5
  - 3.6

install:
  - pip install pipenv
  - pipenv install --three
  - pipenv install --ignore-pipfile
  - pipenv install --dev --ignore-pipfile

script:
  - pipenv run coverage run setup.py test
  - pipenv run coverage report
