language: python
python:
- 3.5
- 3.6
env:
  global:
  - secure: InlGRPpD8bfwdK5QSsXPqdRaIaNG6iLC9LKHkBvcZhNzQQoDmGUoy2K+6OAftABXjaF1IBeRRfx5A+N+afJIhwA7rKHLUB2ItlirN7M2aVAOEoEhP2ilscT+OsJi4mUGbF6QDTvfNhjAbJwTkBwOP9MQ7NATxAmlqiiFzQ0mOZpevbr/4X0+MMr0ypweZiezlz5OrPUlMuJkCJIDQPAPEMZy+mh5DCdLpdA0mynGXpAEBZ7OwSn0QcrnDVezW5DM8qPcyVy4t++CQ22Jte/636xdDzNPpav1jm+urje6/3PbdZ6a2asL27eUtIJgqHE3+06oXt07+LjyaWJl6ooa1LhzeDnnj4npB0Cs3b3soboATwRpCWIj446rs75L/DeZRKf5XVwePsnjxW6WGII0U4KnCv4jdxw0qzs/mieywWsFlrUzYIvGpujzypmP4DJ9Djc5/jeAVMvKSKIVVa90cAJ1ouy50P54kquwduh6fvFxlb8kBP/DGnziHFiVf4Jq0pDzRwJQIZgdIHP8eXJghsHxs9u32M5u8MXX4LXpW7eLla9G6PTGq20Vpo7bFqdb3GRgq9NFQOUxN8NCWSG/DlvrapRRmLnrtqHp+SQPYsaHtKEvGtgjJhSSHFGgI926lZt8ogosEvZVOcr/FOAaozxPBvVqEtEucJUDgajuxFc=
  - PYPI_USER_NAME: singhgarima
install:
- pip install pipenv
- pipenv install --three
- pipenv install --ignore-pipfile
- pipenv install --dev --ignore-pipfile
script:
- bash ci.bash
