language: python
python:
- 3.5
- 3.6
deploy:
  provider: pypi
  user: singhgarima
  password:
    secure: ENC3kuAbXsO3fL4depbLg/PRV6YvaRx+owd/yfAAtRLcSPaVxezuiIUh5V8xTIuH3TvcAeFhp60SqttqOr1/Ij0gfn7+jm6rmk4sbH9vOKH83AAlFcDar4qoh3VmtuugFWokHTI36tb92Brra7nUBuFYUC6xBanaeM8qTUH21t6CGPKcP7kYV3SWYaQK3brhneKKu973X6TfqenJoBCLVYTGGKa4xb94hqCXyILUH/a8Pet1uJrUGQbDK7TGgPfK8MpDGockBtbP1b0n/+R7xUvAeaDrxuajayVuVJOvD60DpQuQGuf5dc0q59DKWvsIq/cdOYboJ21VO3hxXLhI5qAP+ZImKSuMkziunVWdUTrviA9I/Xso4jrW1zvlCYcs3lb1jtZydy/NK5CSgLK+3XqXs2LSTsLFXJO4JZ7mXAXKc79X2WoxF+1WAQdxRXrF/IleeugaB0WhiifCzOY2Jx5rfZX+Y0L439IZfthiXW1iRFtbBwEfcYIqfR6IWeP3STpkmFvPt5ggFO2U2PJt9ZD3J/5pf6yavJDrSsh1NRkTsENHEBKhINe4hl3I5o3MibFkcxd9rDqsGteoWJo00+bMsl9CsMG5CejaUzOlHGNBdm1fKmeEJvMuvZUfmWcXecqAZld9bkyEP//rl1IeEyeBfF/HomG8P5w6LCRpaac=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
install:
- pip install pipenv
- pipenv install --three
- pipenv install --ignore-pipfile
- pipenv install --dev --ignore-pipfile
script:
- pipenv run coverage run setup.py test
- pipenv run coverage report
