language: python
python:
- 3.5
- 3.6
env:
  global:
  - secure: YwlEraS5c2uhOSw/BkKt44qE5iig7/DqLYS+XMCf1BgDfpKxVgCJmP4nJaLlMfgwATFT+vzU1cuVCybMMKTXcNHCf9BeHSgDKmbx2c6kzqFEG/rJW+BvR1RkaGhiLth4EfgeelnSwiaO9pzwU3nheH1D41L4eaQFT41UcviOk2iMP10Lpqhjwz2wdS3w+9wg/HYoBmVkWcT5e44DIxn67QmHoqCSaOGEf0RR7pmbRTN4fJm6+BuGYC0VYfKVg/eqC+nGi54/UHZDiuQ9E2JjqhlGF7lZ2fffa8RJCZO1wlC/jRFEk1aTs+eukRecaaG5ojpT4oSWa1Xxcrase8hJ64vRsG8Wle3yBUgcCr35vE4Zdw34fnFMnP+kOkLCPo7JFMw7svahXmCf/Xbe6hOUnz/hxBGoN/KaktfCwnWtaG4mGD8ArZoTNNqpticjE7OduBBL+6eYlF+NSOibtTCRs/E0uvvKYJIoxfeViB0m6p8P1aRSiA1v+oKiSiiS4gZ1ur2MIAFdjiHmmJfIN6Fmg8H2sle6YTv1611MARgayJcR4n6IBBKyb5KgpwUUlz2f35uC8u5pD9El8JzwfK9R38oNteflxqItQeYViqRRT8TJkIjf/RJr/McnVyp6JfPBiuThfJ8HHAzZf0lJ8ROTpI1kEpaAHk+51iRLrFT0a1M=
  - PYPI_USER_NAME: singhgarima
install:
- pip install pipenv
- pipenv install --three
- pipenv install --ignore-pipfile
- pipenv install --dev --ignore-pipfile
script:
- bash ci.bash
