language: python
python:
- 3.5
- 3.6
deploy:
  provider: pypi
  user: singhgarima
  password:
    secure: d3KEJH3Qlsjn0huYk2acYP5YI3ulD9xW2KNq/ijnTAXQx592ykNtDKhifIANKBHoz8JCWgY+FKQmg2nqcYC7nEurQLVj6IGnBOVBK1gk7/eVap2Tma64vwdFyus1tz4nzJpfUzmaLi6kld27h15PlPc+AP6H3Ur7Jo2WxA7UUsAy8D5saC6VCHz7CnBf6lE4j3YJ2JJlTW711LgTg8+dlas1y8m5GSBmYqhlbL5ih5rs3VUjb1R7MIhFVoj1i3YEh8poQHYyUQCVCHUD5qChKKfeHH2sFI8jCFDkWmQSm3uFM2WQm2PbDEyHLe8+8ABhJsRDkQq6iJeFq8/MA2kUQvJu4Bk2Qidi37sZXWAbpCd9seE0AM3DQdLSHSJyt+a92Lwh8p6ZkLcPYBc0IW8d8CQrPWwWL67TuoGsZBwSx+x+cn1smbqS/ymkUGOvW2v1pLoWrHUzP0e5i+y3nKAzqt3fxorXYfQpCXiNe6y8LkDi1MPuRklPjfjvyoJ4CpIHXFVOUKY3yQXSt3c8aCEAE+wFuiifWhNF+w92/kyRawjZheqLiVAdO7FRLCsnmgK76i/6AlXQ7RpOWIExkD/ZbPZqxlBBo5TCn8ORxU4eOtvrA9iFu5SyfcavswQwCIgk/7R5kflM7yW0qCNuCM5dKCLafqVuO/1d2SAKEawrtxg=
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$"
install:
- pip install pipenv
- pipenv install --three
- pipenv install --ignore-pipfile
- pipenv install --dev --ignore-pipfile
script:
- bash ci.bash
